### ISSUE TITLE
£15bn economic impact

### ISSUE THREAD

**Issue by davidread** [publicdigital/open-source-in-government#1]
> the Government Digital Service (GDS) built its new procurement framework around a philosophy of buying either teams to help build a service, or commodities that do not require customisation. This – coupled with the push from within GDS and other parts of the UK Government to use open source software, and code in the open – led to open source being a ~£15bn contributor to the UK economy[^23]

> [[^23]: Open UK (2021) State of Open: The UK in 2021](https://openuk.uk/wp-content/uploads/2021/03/openuk_stateofope2021_report_FINALCHANGES_08.pdf)

Am I correct to say that you're using the numbers for the annual economic impact of open source in the UK, as given on page 14 of that Open UK report? And you're suggesting that GDS and the UK Government are behind the majority of that impact?

**Comment by annahirschfeld** [comment]
Hi David, thank you for pointing out the error on page 26 of the report. I have updated the language to make it clear that GDS and the UK government contributed to the economic impact rather than being responsible for the majority of the impact.
